"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
    { on = [ "g", "d" ],       run = "cd ~/devs",   desc = "Goto ~/devs" },
    { on = [ "g", "B" ],       run = "cd /backtests/",   desc = "Goto Backtests" },
    { on = [ "g", "q" ],       run = "cd ~/devs/Qubx",   desc = "Goto Qubix" },
    { on = [ "g", "x" ],       run = "cd ~/projects/xincubator",   desc = "Goto xIncubator" },
    { on = [ "g", "R" ],       run = "cd ~/projects/xincubator/research",   desc = "Goto Research" },
    { on = [ "g", "h" ],       run = "cd ~",             desc = "Go home" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",     desc = "Goto ~/.config" },
	{ on = [ "g", "<Space>" ], run = "cd --interactive", desc = "Jump interactively" },
    { on = "~", run = "cd ~", desc = "Go home" },
    { on = ";", run  = "plugin jump-to-char", desc = "Jump to char"},
    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = [ "E" ], run = "plugin eza-preview",  desc = "Toggle tree/list dir preview" },
    { on = [ "m" ], run = "plugin bookmarks save",  desc = "Save current position to bookmark" },
    { on = [ "`" ], run = "plugin bookmarks jump",  desc = "Jump to bookmark" },
    { on = [ "b", "d" ], run = "plugin bookmarks delete",  desc = "Delete bookmark" },
    { on = [ "b", "D" ], run = "plugin bookmarks delete_all",  desc = "Delete all bookmarks" },
    #{ on = ":", run = "plugin shell --args=--block", desc = "Default shell with blocking" },
    { on = [ "<c-o>" ], run = 'shell "$SHELL" --block',  desc = "Open $SHELL here" },
    { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'}
    #{ on = [ "<esc>" ], run = 'close'}
]
